### ISSUE TITLE
setting not working correctly

### ISSUE THREAD

**Issue by Quenom** [SoSeDiK/YAGS#3]
in setting option "auto attack" doesnt do anything
"lazy combat mode" controlls both rmb to charge attack and normal attack spam on lmb

**Comment by Quenom** [comment]
nvm i just realized "auto attack" controls autoattacks on V
still tooltips are wrong then + it would be nice to be able to use only rmb from lazy combat mode, without normal atttack spam on lmb

**Comment by SoSeDiK** [comment]
Nice catch, the tooltip was indeed wrong, corrected it.

As for the suggestion, is there any reason why you'd prefer only `RMB` functionality from lazy combat?
Since then it will be the same as holding `LMB` with no extra benefits 🤔

**Comment by Quenom** [comment]
i like the idea of separating inputs + when I'm trying to do tighter combos on catalyst users sometimes I'm not holding the button long enough to register as charged attack, i also remember about that being a problem for hu tao

**Comment by SoSeDiK** [comment]
Done. Let me know if anything needs tweaking
