### ISSUE TITLE
"Menu Clicks" breaks hold mmb for elemental sight

### ISSUE THREAD

**Issue by Quenom** [SoSeDiK/YAGS#4]

**Comment by SoSeDiK** [comment]
MMB for camera reset/elemental sight should now work if `AutoWalk` is disabled.
(MenuClicks shouldn't interfere with this)

There's also `H` hotkey for `AlternateVision` which allows elemental sight without MMB if AutoWalk is wanted.

Let me know if something's wrong! :)

**Comment by Quenom** [comment]
seems like i should specify what was the problem, forgot sry
mmb would do normal attack as if "menu clicks" wasnt correctly reading that im not in a menu
anyways, seems like it's fixed now
(i didnt use autowalk)
![image](https://github.com/SoSeDiK/YAGS/assets/30837190/39cd2a4e-34d3-456a-81cd-4eb6bae67ac1)
