### ISSUE TITLE
Dialogue skipping Xbutton1 doesnt do anything

### ISSUE THREAD

**Issue by Quenom** [SoSeDiK/YAGS#5]
doesnt seem to be a problem with swaping xbutton1 and 2
xbutton1 works correctly for lazy sigil
![image](https://github.com/SoSeDiK/YAGS/assets/30837190/fedd06f5-efe0-4218-a6d6-f7970e63e05a)

**Comment by SoSeDiK** [comment]
Seems like `XButton1` dialogue skipping was tied to `Quick Pickup` (hold to spam `F`).
Should be fixed now
