### ISSUE TITLE
Autorun dash timing

### ISSUE THREAD

**Issue by Mockii7** [SoSeDiK/YAGS#6]
Is it possible to adjust the timing of the dashes you do when you autorun? Would like the chars to double dash, wait a bit till the used up stamina is regenerated and then double dash again. Afaik this is the best and fastest way for a sustained run in genshin.

**Comment by SoSeDiK** [comment]
Hello!
Sure, I can look into this if still needed 😀
I wasn't aware of this way to run. Is there any video showcasing this running? (just to be sure)
