### ISSUE TITLE
Better Map Click problem with the 4.2 UI update

### ISSUE THREAD

**Issue by PunnDaa** [SoSeDiK/YAGS#7]
After the 4.2 UI update, the Better Map Click half of the time doesn't work properly.

In line 1842, (and 1896, similar problem)
{ X1: 1478, Y1: 1012, X2: 1478, Y2: 1013, Color: "0xFFCD33" } should also be changed to 
{ X1: 1478, Y1: **1006**, X2: 1478, Y2: **1007**, Color: "**0xFFCB33**" }
following the position and color change in line 1880 of version 1.1.3.

**Comment by SoSeDiK** [comment]
Thanks! Should be working now 😄
